### ISSUE TITLE
에러포맷 바꾸기

### ISSUE THREAD

**Issue by goyarn** [NavyBye/ft_transcendence#103]
이제 에러가 생겼을 때에는 redirect 나 message 같은 타입을 먼저 명시하게 하기로 했어요
```
{
  type: 'message'
  message: 'blah blah'
}
혹은
{
  type: 'redirect'
  redirect: 'home'
}
```
같은 식으로... 생각날때마다 고치도록 하겠습니다.

**Comment by hygoni** [comment]
{
    type: 'redirect',
    target: 'home'
}
으로 갑시당

**Comment by goyarn** [comment]
넵

**Comment by hygoni** [comment]
private ChatRoom join할 때 메시지 포맷 안맞아요
바꿔주세용

**Comment by goyarn** [comment]
game_player / game_queue 의 user_id uniqueness validation 에러메시지가 뭔뜻인지 모르게 나옴(User has already been taken)
나중에 에러관련 작업할때 이를 좀더 알아보기 쉽게 바꿔주자

**Comment by goyarn** [comment]
closed by #197 , 에러메시지에 문제가 있다면 다시...?
