### ISSUE TITLE
ban / mute / free backend 구현 + 논의가 필요한 부분

### ISSUE THREAD

**Issue by hygoni** [NavyBye/ft_transcendence#136]
일단 구현이 필요한 부분은 아래와 같습니다.

뮤트
- 뮤트 당했을 때 메시지 띄우기 (?)
- 메시지 거르기

밴
- 밴 당했을 때 메시지 띄우고 추방 (?)
- 메시지 거르기
- 채팅 못 보게 하기

free
- free되었을 때 알려주기(?)

좀 생각해봐야 할 건, (?) 로 되어있는 부분이 Notification인가 Signal인가 하는 부분입니다.
아 뭔가 쓸게 더 있었는데 곰곰히 생각해볼게요

**Comment by goyarn** [comment]
굿
여기에 꼽사리로 게임신청(래더토너먼트, 친선전) 거절될 시 신청한 사람에게 보내줄 시그널도 정했으면 좋겠습니다

**Comment by hygoni** [comment]
@xcvdv @DiceMono 
admin/unadmin/ban/mute/free
신청은 API -> controller 쪽에서 Chat으로 전달

가능한지 확인해봐주신다고 합니닷

**Comment by hygoni** [comment]
드디어!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!1ㅍ
