### ISSUE TITLE
friend 상태 전환 실시간

### ISSUE THREAD

**Issue by hygoni** [NavyBye/ft_transcendence#137]
한줄 알았는데 아니었...

**Comment by xcvdv** [comment]
??이거 안되나요?

**Comment by goyarn** [comment]
로그아웃 안하고 나가버리는 거 잡으려면 조금 고쳐야 할거 같아요

**Comment by hygoni** [comment]
프론트 엔드에서 Friend Channel 접속 하는 코드 넣어둘게용
백엔드 에서도 어떤 유저가 unsubscribed 할때  - 다른 유저들한테 broadcast 하도록 넣어주세요!
![image](https://user-images.githubusercontent.com/50040414/118076235-a06bb880-b3ec-11eb-809b-df4864dae339.png)

**Comment by hygoni** [comment]
이거 수정 해주세염

아직 없네유

![image](https://user-images.githubusercontent.com/50040414/119621875-98c2ff80-be41-11eb-899e-22800806faf1.png)

**Comment by goyarn** [comment]
세션을 갖고 하고있는 이상 다중 브라우저/탭을 동시에 고려하며 대응하기는 너무 힘든 거 같습니다. 필요하다면 그냥 friend channel 을 통해서 on/off 만 시키는 게 좋은 거 같아요. 요 이슈는 닫을께요.
