### ISSUE TITLE
match making 오류

### ISSUE THREAD

**Issue by hygoni** [NavyBye/ft_transcendence#156]
@goyarn 
![image](https://user-images.githubusercontent.com/50040414/119125980-65f9bf80-ba6d-11eb-996c-e69fd1e38e78.png)

**Comment by goyarn** [comment]
+ GameQueue 에서 params[:addon] 을 그대로 갖다넣어서 이걸 안 주면 nil을 그대로 넣은것으로 동작해서 에러남
이것도 해결하자

**Comment by goyarn** [comment]
game_player / game_queue 에서 아마 user_id 가 unique 일텐데 이것 validation 시에 나오는 에러 메시지 조정해보기

**Comment by hygoni** [comment]
One more bug!
Good evening lol...

![image](https://user-images.githubusercontent.com/50040414/119138494-ea077380-ba7c-11eb-99a1-1be18c4b1def.png)

`
NoMethodError (undefined method `send_start_signal' for #<User status: "game", nickname: "fart", email: "hyeyoo@student.42seoul.kr", trophy: 0, id: 1, image: nil, created_at: "2021-05-21 16:58:34.418614000 +0900", updated_at: "2021-05-21 21:35:19.539650000 +0900", name: "hyeyoo", provider: "marvin", uid: "69112", rating: 1500, rank: 1, is_banned: false, is_email_auth: false, unique_session_id: "tYQsQfpprJahaA1cEFTr", role: "user">):`

**Comment by hygoni** [comment]
ㅠㅠ #158 로 해결된 줄 알았으나... NoMethodError
![image](https://user-images.githubusercontent.com/50040414/119451791-9d6bb300-bd70-11eb-96df-88d77b514e6d.png)

**Comment by goyarn** [comment]
#163 으로 고쳐진 거 맞죠?

**Comment by hygoni** [comment]
예!
