### ISSUE TITLE
게임 이슈 몇가지

### ISSUE THREAD

**Issue by hygoni** [NavyBye/ft_transcendence#208]
![image](https://user-images.githubusercontent.com/50040414/120162055-f933b180-c232-11eb-8700-4cb1b3a72b96.png)

1. /api/users/:user_id/game 이 안됩니다. (게임중이 아닐땐 그냥 텅 빈 JSON이 오는데, 게임중일 땐 저런 에러가 뜹니다)
2. 게임이 끝난 후 status 갱신이 안됩니다

@goyarn  @goyarn @goyarn

**Comment by goyarn** [comment]
1번 부분은 #206 에서 머지했고, 나머지는 #245 에서 다루겠습니다
