### ISSUE TITLE
채팅이 두번 뜨네요 

### ISSUE THREAD

**Issue by hygoni** [NavyBye/ft_transcendence#48]
채팅이 두번 뜨네요
채팅이 두번 뜨네요

왜지
왜지

**Comment by xcvdv** [comment]
어떤 상황에서 두번 뜨는지 확인 가능한가요?

**Comment by xcvdv** [comment]
backbone.history.loadurl(backbone.history.fragment); 부분 추가로 두번 생성되는 view가 있었네요.
