### ISSUE TITLE
/api/chatrooms에서 joined를 추가해주세요

### ISSUE THREAD

**Issue by hygoni** [NavyBye/ft_transcendence#59]
현재 내가 이 채팅방에 참가했는지, 아닌지를 판단하려면 지금

/api/chatrooms/:id/members를 조회해서 내가 포함되어있는지 아닌지 매번 조회해야 하는데,
그것보단 /api/chatrooms에서 해당 목록을 조회한 유저가, 채팅방에 포함이 되어있는지 보내주는 게 좋을 것 같습니다

아래는 예시입니다.
[{"id":21,"name":"a","public":true, joined: true},{"id":23,"name":"bcd","public":true, joined: false}]

**Comment by DiceMono** [comment]
api/my/chatrooms api 추가했습니다.
