### ISSUE TITLE
사용자가 입장하지 않은 chatroom의 경우 채팅을 보내거나 메시지를 요청할 때 4XX번대 응답을 날려주세요

### ISSUE THREAD

**Issue by hygoni** [NavyBye/ft_transcendence#60]
지금 패스워드가 있던 없던, 사용자가 입장하지 않은 방에 대하여 메시지를 조회하고, 채팅을 보내는 것이 가능합니다.
ChatRoomsUsers에 현재 존재하지 않는 유저의 동작은 거부해주세요.

**Comment by DiceMono** [comment]
#67 에서 조회에 대한 거부는 추가했습니다. 이후 채팅 보내는 것도 수정하겠습니다.

**Comment by hygoni** [comment]
![image](https://user-images.githubusercontent.com/50040414/119622588-3f0f0500-be42-11eb-9405-83c8c0c15b9b.png)

이슈 닫고싶은데 이거 코드상 처리하는 부분이 없는거같아여
