### ISSUE TITLE
/api/users/:user_id/friends에 user_id 또는 user를 추가해주세요.

### ISSUE THREAD

**Issue by hygoni** [NavyBye/ft_transcendence#62]
response에서 name밖에 주지 않는데, followee의 id나, user 객체를 반환해주면 좋을 것 같습니다.
(일단 id가 필요해요)

**Comment by goyarn** [comment]
이 이슈 문제가 뭔지 모르겠어요
제가 친구관계 만들어서 실제로 확인해보면 [{id, name, status}, {id, name, status}] 와 같이 잘 반환됩니다

컨트롤러 고치려고 들여다보면서 name 만 나오는게 맞나 싶어서 nickname 도 나오게 하긴 했는데 어떤식으로 나오나요

**Comment by hygoni** [comment]
제가 자꾸 헷갈리는 것 같습니다 ㅠㅠㅠ

아까 것도 그렇고, 무의식적으로 friends#index를 호출하면 DB상의 friend에 대응되는 것을 넘겨준다고 생각하고 있었어요.
실제로는 user 모델을 넘겨주도록 되어있군요.

**Comment by hygoni** [comment]
클로즈 하겠습니다
