### ISSUE TITLE
BlockController의 create부분 validation? 을 수정해주실 수 있나요

### ISSUE THREAD

**Issue by xcvdv** [NavyBye/ft_transcendence#64]
ArgumentError in Api::BlocksController#create

wrong number of arguments (given 2, expected 1)
Extracted source (around line #501):
#499     #
#500     # for example.
*501     def require(key)
#502       return key.map { |k| require(k) } if key.is_a?(Array)
#503       value = self[key]
#504       if value.present? || value == false
Extracted source (around line #21):
#19 
#20     def block_params
*21       params.require(:user_id, :blocked_user_id)
#22     end

backbone기본으로 있는 Create를 사용해 block model을 생성합니다. 이때 POST요청 body에 user_id, blocked_user_id두개가 모두 전송됩니다.  현재 위와 같은 response가 오고 500 server error가 발생하는데 수정 가능한가요?

**Comment by goyarn** [comment]
21번째 줄 require 를 permit 으로 바꾸면 됩니다 ㅠㅠ 테스트 안한 스노우볼
