### ISSUE TITLE
block user destroy...HELP

### ISSUE THREAD

**Issue by xcvdv** [NavyBye/ft_transcendence#70]
web_1  | Processing by Api::BlocksController#destroy as JSON
web_1  |   Parameters: {"user_id"=>"1010528734", "blocked_user_id"=>"1010528735"}
web_1  | Unpermitted parameter: :format

위에는 서버 LOG입니다. 
unblock을 위해 아래의 URL로 DELETE 요청을 보냈습니다.
api/users/{user_id}/blocks/{blocked_user_id} 

가장 처음 404 Error가 발생하였으며 blocksController에서 delete를 destroy로 변경하니 위에 첨부한 LOG가 발생하였습니다. 
HELP

**Comment by xcvdv** [comment]
![image](https://user-images.githubusercontent.com/46748648/116395309-ebb79000-a85e-11eb-8d62-6ed359297647.png)

**Comment by goyarn** [comment]
destroy로 바꾼 거는 맞는거같고
제가 탐색만 하고 destroy를 안 하기도 했고 no_content 라면서 반환값도 주고 등등 각종 손안댄 부분이 너무 많네요
근데 이걸 destroy 로 돌린 후에 왜 unpermitted parameter 가 떴는지는 저도 모르겠습니다.

일단 반환값 없애버리고 pr 해보겠습니다.
