### ISSUE TITLE
kick/(un)ban/(un)mute 기능 추가

### ISSUE THREAD

**Issue by hygoni** [NavyBye/ft_transcendence#72]
추가해주세용

**Comment by hygoni** [comment]
@DiceMono 
챗 admin / unadmin도 넣어주세용

**Comment by DiceMono** [comment]
> @DiceMono
> 챗 admin / unadmin도 넣어주세용

PUT chatroom members api 이써요

**Comment by hygoni** [comment]
아하 알겠습니당
