### ISSUE TITLE
SIdeview 세부 구현

### ISSUE THREAD

**Issue by xcvdv** [NavyBye/ft_transcendence#75]
- ChatRoom
  - [x] Private일 때 비밀 번호 요구 
- Chat
  - [x] kick, (nu)ban, (nu)mute, (un)admin
  - [x] block된 user msg 처리 -> 아예 안보이도록
- UserProfileModal
  - [x] block test
  - [x] follow, unfollow -> 상태에 따라 보이는 버튼 다르게 수정 필요
  - [x] Guild invite -> 현재 자신이 길드의 officer, admin일때만 버튼 활성화 되도록(필요한가?)
  - [x] DM button 기능 추가
 - DM
   -  [x] DM 구현

**Comment by xcvdv** [comment]
추가 - addChatroom했을 때 자동으로 해당 방에 join되도록해야함

**Comment by hygoni** [comment]
> 추가 - addChatroom했을 때 자동으로 해당 방에 join되도록해야함

이건 백에서 처리해주어야 하지 않을까요?

**Comment by hygoni** [comment]
거의 다 됐다~~
