### ISSUE TITLE
PUT으로 변경할 때 이렇게 되어도 괜찮은건가요?

### ISSUE THREAD

**Issue by hygoni** [NavyBye/ft_transcendence#83]
Backbone model에서 save로 업데이트 하면 저렇게 모든 필드가 들어가고,
서버 측에서는 저렇게 뜨네요. 상관 없나요?

부분적으로 수정하려면 서버에서 PATCH를 지원해야 해요.
![image](https://user-images.githubusercontent.com/50040414/116772422-f0ac5780-aa89-11eb-939d-c760f4d6ceb5.png)

**Comment by hygoni** [comment]
수정 자체는 잘 됩니다

**Comment by goyarn** [comment]
별 문제는 없고 무엇보다 레일즈에서 기본적인 Update연산 쓰려고 하면에 PUT PATCH를 구분 안해서 이렇게 해도 괜찮을 거 같습니다
비효율적인 부분은 있는 것 같은데 이건 제가 나중에 수정하겠습니다

**Comment by hygoni** [comment]
네 감사합니다

**Comment by hygoni** [comment]
아 근데 PATCH로 보내도 상관 없는건가요 그럼??
Documentation에 없길래 그냥 PUT으로 보낸거였어요

**Comment by hygoni** [comment]
상관 없답니다. ClOsE iSsUe!
