### ISSUE TITLE
Rails에서 Redirect 안 하게 해주세요.

### ISSUE THREAD

**Issue by hygoni** [NavyBye/ft_transcendence#86]
라우터에서 자꾸 오류나는 부분이, Backbone.Router를 통하지 않고
Rails에서 그냥 redirect_to로 리다이렉트 하는 부분이 많은 것 같아요

특히 로그인/로그아웃 할 때 리다이렉트 안 되게 해주세요.

**Comment by hygoni** [comment]
![image](https://user-images.githubusercontent.com/50040414/116841530-7bb95900-ac14-11eb-9ba9-e252dd51138d.png)

**Comment by hygoni** [comment]
42 Auth 로그인하니까 리다이렉트가 좀 이상하게 되네요

**Comment by goyarn** [comment]
42로그인은 다시 리다이렉트로 바꿨어요~

**Comment by hygoni** [comment]
삽질 기록:
- Custom Login을 Redirect 안 하도록 바꿨더니 Login 후 CSRF Token Verification 오류남
- 그래서 로그인 시 form_authenticity_token 리턴값으로 토큰을 갱신했더니 그래도 안됨

Devise가 문제인가 Rails가 문제인가
SPA에서 Rails, Devise 쓰는걸 찾아봐야겠어요

**Comment by hygoni** [comment]
문제점 
- devise에서 sign_in시 token을 리셋함
- $.ajaxSetup은 새로 갱신된 토큰이 반영이 안되고 맨 처음 사이트 로딩시 받은 토큰으로 계속 보냄
- -> can't very token!
